config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'persons/profile'

  get 'persons/profile', as: 'user_root'
  resources :prices

  root 'view#General'
  get 'view/General'
  resources :products

  get "view/Contact" => "view#Contact"

  get 'admin/edit'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/price.rb
class Price < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def edit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
     root_path
  end
  def after_sign_out_path_for(resource_or_scope)
  	request.referrer
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  protect_from_forgery with: :null_session
  def new
    @price = Price.new
  end

  def create
    @price = Price.new(price_params)
   
    if @price.save
      
      flash[:notice] = "Позиция добавлена"
      redirect_to prices_path
    else
      render :action => 'new'
    end      
  end

  def show
    @price = Price.find(params[:id])
  end

  def index
    @index = 0
    @prices = Price.all
  end

  def edit
    @price = Price.find(params[:id])
  end

  def destroy
    @price = Price.find(params[:id])
    @price.destroy
    flash[:notice] = "Продукт удален."
    redirect_to prices_path
  end

  private
    def price_params
      params.require(:price).permit(:name, :description, :price)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
protect_from_forgery with: :null_session
  def index
  	@products = Product.all
  end

  def new
  	@product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:notice] = "Продукт обновлен."
      redirect_to product_url
    else
      render :action => 'edit'
    end
  end

  def show
  	@product = Product.find(params[:id])
    
  end

  def create
    @product = Product.new(product_params)
   
    if @product.save
      
      flash[:notice] = "Продукт добавлен"
      redirect_to @product
    else
      render :action => 'new'
    end      
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Продукт удален."
    redirect_to products_path
  end
  private
    def product_params
      params.require(:product).permit(:id, :name, :desc, :image, :price)
    end
end

app/controllers/view_controller.rb
class ViewController < ApplicationController
  def General
  end

  def Contact
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/price_helper.rb
module PriceHelper
end

app/helpers/view_helper.rb
module ViewHelper
end

app/views/admin/edit.html.haml
%h1 Admin

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title 
      Crane
    %meta{charset: 'utf-8'}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 

  %body
    #head

      #contact
        #c1
          = image_tag("crane.png", :height => "150px");
        #c2
          ПО Кран
          %br Диагностика
        #c3
          +7 (499) 798-02-10
          %br +7 (906) 735-03-97
          +7 (925) 739-12-32
        #c4
          #in
          - if user_signed_in?
            = link_to "Выход", destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: 'delete'
          - else
            = link_to "Вход", new_user_session_path
           
          = image_tag("crane1.jpg", :height => "150px");

        .cl  

      #menu
        = link_to "Главная", root_path 
        = link_to "Продукты и цены", products_path
        = link_to "Прайс", prices_path
        %a{:href => "#"} Тех. поддержка
        = link_to "Контакты", view_Contact_path
      #gallery

    #body

      #left
        #price
          .head_block
            Прайс
            %span{:style => "float: right;"}
              = image_tag("crane.png", :height => "40px");
            .cl  
            = render "prices/index1", prices: Price.all
        #tech
          .head_block
            Тех. поддержка
            %span{:style => "float: right;"}
              = image_tag("crane.png", :height => "40px");
            .cl  
      #right
        = yield 
      .cl  

    #footer

      #address
        %span.b
          "ПО Кран диагностика"
          %br 
          Адрес:
        Россия, Москва, ул. Верхоянская 
        %br дом 6 кор.1 офис 12129344  
        %span.b
          Email:
        arf_petr70@mail.ru   
        
      #call
        %span.b
          Тел: 
        +7 (499) 798-02-10
        %br +7 (906) 735-03-97
        +7 (925) 739-12-32
        %br
          %span.b
            Контактное лицо: 
          Петр Арефьев 
      .cl

app/views/persons/profile.html.haml
%h1 Persons#profile
%p Find me in app/views/persons/profile.html.haml

app/views/prices/_form.html.haml
.body
  = form_for(@price) do |f| 
    = f.text_field :name, label: "Название", :placeholder => "Название", :wrapper => false, input_html: {:class => "form-title"}  
    %br
    = f.text_field :description, label: "Обозначение", :placeholder => "Обозначение", :wrapper => false, input_html: {:class => "form-title"}  
    %br
    = f.text_field :price, label: "Цена",:placeholder => "Цена", :wrapper => false, input_html: {:class => "form-title"} 
    %br
    = f.submit "Сохранить", :class => "btn btn-success pull-right"
    = link_to "К списку продуктов", prices_path, :class => "btn btn-default" 

app/views/prices/_index1.html.haml
%table{:style => "width: 100%; "}
  - unless prices.nil?
    - for price in prices
      %tr
        %td.l.nb{:style => "padding-left: 10px;"}   
          = price.name
        %td.nb{:style => "padding-left: 10px;"}   
          = price.price
          р.

app/views/prices/edit.html.haml
%h1 Price#edit
%p Find me in app/views/price/edit.html.haml

app/views/prices/index.html.haml
.head_block
  Прайс
%table.t
  %tr
    %th № п.п.
    %th Наименование продукции
    %th Обозначение
    %th Цена
    %th.nb
  - for price in @prices
    %tr
      %td{:style => "text-align: center;"} 
        - @index+=1
        = @index
      %td{:style => "padding-left: 10px;"}  
        = price.name
      %td{:style => "padding-left: 10px;"} 
        = price.description
      %td{:style => "text-align: center;"}  
        = price.price
        р.
      %td.nb{:style => "text-align: center;"} 
        / - if user_signed_in?
        = link_to "удалить", price, data: {:confirm => "Удалить продукт?"}, :method => :delete

-if user_signed_in? 
  .button_add
    = link_to "Добавить позицию", new_price_path, :class => "btn btn-default"

app/views/prices/new.html.haml
.head_block 
  Новая позиция
= render 'form'

app/views/prices/show.html.haml
.head_block
  = @price.name
%table
  %tr
    %th 
      Название:
      = @price.name
  %tr
    %th 
      Обозначение:
      = @price.description
  %tr    	
    %th 
      Цена:
      = @price.price 
      рублей

app/views/products/_form.html.haml
.body
  = form_for(@product) do |f| 
    = f.text_field :name, label: "Название", :placeholder => "Название", :wrapper => false, input_html: {:class => "form-title"}  
    %br
    = f.text_field :image, label: "Ссылка на изображение", :placeholder => "Ссылка на картинку", :wrapper => false, input_html: {:class => "form-title"}  	      
    %br
    = f.text_field :desc, label: "Описание", :placeholder => "Описание", :wrapper => false, input_html: {:class => "form-title"} 
    %br
    = f.text_field :price, label: "Цена",:placeholder => "Цена", :wrapper => false, input_html: {:class => "form-title"} 
    %br
    = f.submit "Сохранить", :class => "btn btn-success pull-right"
= link_to "К списку продуктов", products_path, :class => "btn btn-default" 

app/views/products/edit.html.haml
= render 'form' 

app/views/products/index.html.haml
.head_block
  Список продуктов
.body
  .sc_menu
    %ul.sc_menu
      - for product in @products
        %li
          %div
            %img{:alt => "temp-thumb", :height => "120px", :src => "#{product.image}", :width => "120px"}
          %div
            = link_to raw(product.name), product_path(product)
  -if user_signed_in?          							
    = link_to "добавить продукт", new_product_path, :class => "btn btn-default"

app/views/products/new.html.haml
.head_block
  Новый продукт
= render 'form' 

app/views/products/show.html.haml
%div
  %h1
    = "#{@product.name}"
  .pull-left
%table
  %tr		
    %th
      %img{:alt => "temp-thumb", :height => "200px", :src => @product.image, :width => "200px"}					
  %tr
    %th 
      Описание: 
      = @product.desc 	
  %tr
    %th 
      Цена: 
      = @product.price 
      рублей	
%div
-if user_signed_in? 
  = link_to "Редактировать", edit_product_path, :class => "btn btn-default" 
  = link_to "К списку продуктов", products_path, :class => "btn btn-default" 
  = link_to "Удалить", @product, data: {:confirm => "Удалить продукт?"}, :method => :delete, :class => "btn btn-danger" 
		   

app/views/view/Contact.html.haml
.head_block
  Контактная информация
%table.contact
  %tbody
    %tr
      %th.contact Название:
      %td.contact ООО "ПО Кран диагностика"
    %tr
      %th.contact Контактное лицо:
      %td.contact Петр Арефьев
    %tr
      %th.contact Адрес:
      %td.contact РоссияМоскваВерхоянская дом 6 кор.1 офис 12129344
    %tr
      %th Телефоны:
      %td.contact_r +7(499)798-02-10 
    %tr 
      %th
      %td.contact_r +7(925)739-12-32  
    %tr
      %th 
      %td.contact_r +7(906)735-03-97
  %tbody

app/views/view/General.html.haml
.head_block
  Главная